CXX=g++
CXXFLAGS = -g -Wall -pedantic -std=c++14
LD=g++
LDFLAGS= -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer

HEADERS = $(wildcard src/*.h)
SOURCES = $(wildcard src/*.cpp)
OBJECTS = $(SOURCES:src/%.cpp=build/%.o)

.PHONY: all
all: compile doc

.PHONY: run
run: compile
	./Ant_Wars

.PHONY: compile
compile: Ant_Wars

doc: Doxyfile $(HEADERS)
	doxygen Doxyfile

.PHONY: clean
clean:
	rm -rf Ant_Wars build/ doc/ 2>/dev/null

.PHONY: memrun
memrun: compile
	valgrind ./Ant_Wars

.PHONY: test
test: compile
	./Ant_Wars test

.PHONY: memtest
memtest: compile
	valgrind ./Ant_Wars test

Ant_Wars: build/Ant_Wars
	cp $< $@

build/Ant_Wars: $(OBJECTS)
	mkdir -p build
	$(LD) $^ $(LDFLAGS) -o $@

build/%.o: src/%.cpp
	mkdir -p build
	$(CXX) $(CXXFLAGS) $< -c $(LDFLAGS) -o $@

#Generated by "g++ -Wall -pedantic -MM src/*cpp
build/Ant_Wars.o: src/Ant_Wars.cpp src/CApplication.h src/CDatabase.h \
 src/CTexture.h src/globalVar.h src/STextureData.h src/Exceptions.h \
 src/CGame.h src/EColor.h src/CStageDefeat.h src/CStage.h src/CClash.h \
 src/CClickableObject.h src/CHive.h src/CLine.h src/CPoint.h src/CWall.h \
 src/CButton.h src/CTextureText.h src/CCustomEvents.h src/EStage.h \
 src/CMap.h src/EDifficulty.h src/CStageGame.h src/CAI.h src/CStageLoad.h \
 src/CStageMenu.h src/CStageNewGame.h src/CStageSave.h \
 src/CStageVictory.h src/CTests.h
build/CAI.o: src/CAI.cpp src/CAI.h src/CMap.h src/globalVar.h src/CHive.h \
 src/EColor.h src/Exceptions.h src/CClickableObject.h src/CTexture.h \
 src/STextureData.h src/CDatabase.h src/CClash.h src/CLine.h src/CPoint.h \
 src/CWall.h src/EDifficulty.h src/CCustomEvents.h src/EStage.h
build/CApplication.o: src/CApplication.cpp src/CApplication.h src/CDatabase.h \
 src/CTexture.h src/globalVar.h src/STextureData.h src/Exceptions.h \
 src/CGame.h src/EColor.h src/CStageDefeat.h src/CStage.h src/CClash.h \
 src/CClickableObject.h src/CHive.h src/CLine.h src/CPoint.h src/CWall.h \
 src/CButton.h src/CTextureText.h src/CCustomEvents.h src/EStage.h \
 src/CMap.h src/EDifficulty.h src/CStageGame.h src/CAI.h src/CStageLoad.h \
 src/CStageMenu.h src/CStageNewGame.h src/CStageSave.h \
 src/CStageVictory.h src/CTests.h
build/CButton.o: src/CButton.cpp src/CButton.h src/CClickableObject.h \
 src/CTexture.h src/globalVar.h src/STextureData.h src/EColor.h \
 src/Exceptions.h src/CTextureText.h
build/CClash.o: src/CClash.cpp src/CClash.h src/CClickableObject.h \
 src/CTexture.h src/globalVar.h src/STextureData.h src/CHive.h \
 src/EColor.h src/Exceptions.h src/CDatabase.h src/CLine.h src/CPoint.h \
 src/CWall.h
build/CClickableObject.o: src/CClickableObject.cpp src/CClickableObject.h \
 src/CTexture.h src/globalVar.h src/STextureData.h
build/CCustomEvents.o: src/CCustomEvents.cpp src/CCustomEvents.h src/EStage.h \
 src/EColor.h src/Exceptions.h
build/CDatabase.o: src/CDatabase.cpp src/CDatabase.h src/CTexture.h \
 src/globalVar.h src/STextureData.h src/Exceptions.h
build/CGame.o: src/CGame.cpp src/CGame.h src/EColor.h src/Exceptions.h \
 src/CDatabase.h src/CTexture.h src/globalVar.h src/STextureData.h \
 src/CStageDefeat.h src/CStage.h src/CClash.h src/CClickableObject.h \
 src/CHive.h src/CLine.h src/CPoint.h src/CWall.h src/CButton.h \
 src/CTextureText.h src/CCustomEvents.h src/EStage.h src/CMap.h \
 src/EDifficulty.h src/CStageGame.h src/CAI.h src/CStageLoad.h \
 src/CStageMenu.h src/CStageNewGame.h src/CStageSave.h \
 src/CStageVictory.h
build/CHive.o: src/CHive.cpp src/CHive.h src/EColor.h src/Exceptions.h \
 src/CClickableObject.h src/CTexture.h src/globalVar.h src/STextureData.h \
 src/CDatabase.h
build/CLine.o: src/CLine.cpp src/CLine.h src/CClickableObject.h src/CTexture.h \
 src/globalVar.h src/STextureData.h src/EColor.h src/Exceptions.h \
 src/CPoint.h
build/CMap.o: src/CMap.cpp src/CMap.h src/globalVar.h src/CHive.h src/EColor.h \
 src/Exceptions.h src/CClickableObject.h src/CTexture.h \
 src/STextureData.h src/CDatabase.h src/CClash.h src/CLine.h src/CPoint.h \
 src/CWall.h src/EDifficulty.h src/CCustomEvents.h src/EStage.h
build/CPoint.o: src/CPoint.cpp src/CPoint.h src/CClickableObject.h \
 src/CTexture.h src/globalVar.h src/STextureData.h
build/CStage.o: src/CStage.cpp src/CStage.h src/CClash.h src/CClickableObject.h \
 src/CTexture.h src/globalVar.h src/STextureData.h src/CHive.h \
 src/EColor.h src/Exceptions.h src/CDatabase.h src/CLine.h src/CPoint.h \
 src/CWall.h src/CButton.h src/CTextureText.h src/CCustomEvents.h \
 src/EStage.h src/CMap.h src/EDifficulty.h
build/CStageDefeat.o: src/CStageDefeat.cpp src/CStageDefeat.h src/CStage.h \
 src/CClash.h src/CClickableObject.h src/CTexture.h src/globalVar.h \
 src/STextureData.h src/CHive.h src/EColor.h src/Exceptions.h \
 src/CDatabase.h src/CLine.h src/CPoint.h src/CWall.h src/CButton.h \
 src/CTextureText.h src/CCustomEvents.h src/EStage.h src/CMap.h \
 src/EDifficulty.h
build/CStageGame.o: src/CStageGame.cpp src/CStageGame.h src/CStage.h \
 src/CClash.h src/CClickableObject.h src/CTexture.h src/globalVar.h \
 src/STextureData.h src/CHive.h src/EColor.h src/Exceptions.h \
 src/CDatabase.h src/CLine.h src/CPoint.h src/CWall.h src/CButton.h \
 src/CTextureText.h src/CCustomEvents.h src/EStage.h src/CMap.h \
 src/EDifficulty.h src/CAI.h
build/CStageLoad.o: src/CStageLoad.cpp src/CStageLoad.h src/CStage.h \
 src/CClash.h src/CClickableObject.h src/CTexture.h src/globalVar.h \
 src/STextureData.h src/CHive.h src/EColor.h src/Exceptions.h \
 src/CDatabase.h src/CLine.h src/CPoint.h src/CWall.h src/CButton.h \
 src/CTextureText.h src/CCustomEvents.h src/EStage.h src/CMap.h \
 src/EDifficulty.h
build/CStageMenu.o: src/CStageMenu.cpp src/CStageMenu.h src/CStage.h \
 src/CClash.h src/CClickableObject.h src/CTexture.h src/globalVar.h \
 src/STextureData.h src/CHive.h src/EColor.h src/Exceptions.h \
 src/CDatabase.h src/CLine.h src/CPoint.h src/CWall.h src/CButton.h \
 src/CTextureText.h src/CCustomEvents.h src/EStage.h src/CMap.h \
 src/EDifficulty.h
build/CStageNewGame.o: src/CStageNewGame.cpp src/CStageNewGame.h src/CStage.h \
 src/CClash.h src/CClickableObject.h src/CTexture.h src/globalVar.h \
 src/STextureData.h src/CHive.h src/EColor.h src/Exceptions.h \
 src/CDatabase.h src/CLine.h src/CPoint.h src/CWall.h src/CButton.h \
 src/CTextureText.h src/CCustomEvents.h src/EStage.h src/CMap.h \
 src/EDifficulty.h
build/CStageSave.o: src/CStageSave.cpp src/CStageSave.h src/CStage.h \
 src/CClash.h src/CClickableObject.h src/CTexture.h src/globalVar.h \
 src/STextureData.h src/CHive.h src/EColor.h src/Exceptions.h \
 src/CDatabase.h src/CLine.h src/CPoint.h src/CWall.h src/CButton.h \
 src/CTextureText.h src/CCustomEvents.h src/EStage.h src/CMap.h \
 src/EDifficulty.h
build/CStageVictory.o: src/CStageVictory.cpp src/CStageVictory.h src/CStage.h \
 src/CClash.h src/CClickableObject.h src/CTexture.h src/globalVar.h \
 src/STextureData.h src/CHive.h src/EColor.h src/Exceptions.h \
 src/CDatabase.h src/CLine.h src/CPoint.h src/CWall.h src/CButton.h \
 src/CTextureText.h src/CCustomEvents.h src/EStage.h src/CMap.h \
 src/EDifficulty.h
build/CTests.o: src/CTests.cpp src/CTests.h src/CGame.h src/EColor.h \
 src/Exceptions.h src/CDatabase.h src/CTexture.h src/globalVar.h \
 src/STextureData.h src/CStageDefeat.h src/CStage.h src/CClash.h \
 src/CClickableObject.h src/CHive.h src/CLine.h src/CPoint.h src/CWall.h \
 src/CButton.h src/CTextureText.h src/CCustomEvents.h src/EStage.h \
 src/CMap.h src/EDifficulty.h src/CStageGame.h src/CAI.h src/CStageLoad.h \
 src/CStageMenu.h src/CStageNewGame.h src/CStageSave.h \
 src/CStageVictory.h
build/CTexture.o: src/CTexture.cpp src/CTexture.h src/globalVar.h \
 src/STextureData.h
build/CTextureText.o: src/CTextureText.cpp src/CTextureText.h src/CTexture.h \
 src/globalVar.h src/STextureData.h src/EColor.h src/Exceptions.h
build/CWall.o: src/CWall.cpp src/CWall.h src/globalVar.h
build/STextureData.o: src/STextureData.cpp src/STextureData.h
build/globalVar.o: src/globalVar.cpp src/globalVar.h
